version: '3'
services:
  app:
    image: task-management-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"



services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=task_management_service_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  app:
    build: ./
    container_name: 'java-app-task'
    ports:
      - 8080:8080

