services:
  database:
    container_name: tasks-psql
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: task_management_service_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5001:5432"

  app:
    build: .
    container_name: 'tms-app'
    ports:
      - "9898:9898"
    depends_on:
      - database

