server:
  port: 9898

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/task_management_service_db
#    url: jdbc:postgresql://tasks-psql:5432/task_management_service_db
    username: postgres
    password: postgres

  liquibase:
    change-log: db.changelog/liquibase-master.yaml
    enabled: true

  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui

app:
  jwt:
    secret: c2VjcmV0IGtleSBmb3IgdGFzayBtYW5hZ2VtZW50IHN5c3RlbXM=
    tokenExpiration: 1800000
    refreshmentExpiration: 30

